name: Deploy Gatsby blog

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: xmflsct/action-publish-gatsby@v1 
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Github Actions
          email: gh-pages@example.com
