on: 
  push:
    branches:
      - master
name: Deploy Gatsby blog
jobs:
  gitHubActionForNpm:
    name: GitHub Action for npm
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: npm install
      uses: actions/npm@59b64a598378f31e49cb76f27d6f3312b582f680
      with:
        args: install
    - name: deploy
      uses: actions/npm@59b64a598378f31e49cb76f27d6f3312b582f680
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        args: run-script deploy
