name: Deploy Gatsby blog

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Publish Gatsby Site
        uses: xmflsct/action-publish-gatsby@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Github Actions
          email: gh-pages@example.com
